
<div class="flex justify-between items-center mb-6">
    <h2 class="text-3xl font-bold text-brandBrown">Tasks list</h2>

    <a href="<?= WEB_ROOT ?>/tasks/create"
       class="bg-brandBrown text-white px-4 py-2 rounded-lg shadow hover:bg-brandBrown/90 transition">
        + Create new task
    </a>
</div>

<div class="overflow-x-auto bg-white shadow rounded-lg">
    <table class="w-full text-left border-collapse">
        <thead class="bg-brandBrown text-white">
            <tr>
                <th class="p-3">Title</th>
                <th class="p-3">Estatus</th>
                <th class="p-3">Category</th>
                <th class="p-3 text-center">Actions</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($this->tasks as $tas): ?>
                <tr class="border-b hover:bg-brandBeige/30 transition">
                    <td class="p-3"><?= htmlspecialchars($tas->task_name) ?></td>
                    <td class="p-3"><?= htmlspecialchars($tas->status) ?></td>                 
                    <td class="p-3"><?= is_array($tas->category_names) ? implode(', ', $tas->category_names) : '' ?> </td>  
                    <td class="p-3 text-center space-x-2">  

                        <a href="<?= WEB_ROOT ?>/tasks/show/<?= $tas->id ?>"
                            class="text-blue-600 font-semibold hover:underline">🔍Ver</a>


                        <a href="<?= WEB_ROOT ?>/tasks/edit/<?= $tas->id ?>"
                            class="text-green-600 font-semibold hover:underline">
                            ✏️Editar
                        </a>


                        <form action="<?= WEB_ROOT ?>/tasks/delete/<?= $tas->id ?>" 
                            method="POST" 
                            class="inline"
                            onsubmit="return confirm('Are you sure you want to delete this task?');">

                                <button type="submit"
                                        class="text-red-600 font-semibold hover:underline">
                                    🗑️ Delete
                                </button>

                        </form>
                </tr>
                
            <?php endforeach; ?>
        </tbody>
    </table>
</div>







