<h2 class="text-3xl font-bold text-brandBrown mb-6">Detalle de tarea</h2>
<div clas="bg-white shawdow rounded-xl p-8 space-y-4">

<p><strong class="text-brandBrown">Título:</strong><?= $task['title'] ?></p>
<p><strong class="text-brandBrown">Descripción:</strong><?= $task['description'] ?></p>
<p><strong class="text-brandBrown">Estado:</strong><?= $task['status'] ?></p>
<p><strong class="text-brandBrown">Inicio:</strong><?= $task['start-time'] ?></p>
<p><strong class="text-brandBrown">Fin:</strong><?= $task['end_time'] ?></p>
<p><strong class="text-brandBrown">Categotías:</strong><?= implode(',', $task['categories']) ?></p>

<a href="/tasks"
class="bg-brandBrown text-white px-4 py-2 rounded hover:bg-brandBrown/90">Volver</a>

</div>