<h1>Editar categoría</h1>

<form action="<?= WEB_ROOT ?>/categories/update/<?= $this->category->id ?>" method="POST">

    <label>Nombre:</label><br>
    <input type="text" name="categori_name" value="<?= htmlspecialchars($this->category->categori_name) ?>" required>
    <br><br>

    <label>Descripcion:</label><br>
    <textarea name="categori_description" rows="4"><?= htmlspecialchars($this->category->categori_description) ?></textarea>
    <br><br>

    <button type="submit">Actualizar</button>
</form>