<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestor de Tareas</title>
</head>
<body>
    
    <?php include (ROOT_PATH . '/app/views/common/header.phtml'); ?>

    <main calss="container">
        <?=  $this->content(); ?>
    </main>

    <?php include(ROOT_PATH. '/app/views/common/footer.phtml'); ?>
    
</body>
</html>